version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=1234

  auth:
    image: hestm/nbf-auth:latest
    ports:
      - '60000:60000'
    volumes:
      - ./auth:/config
    environment:
      - CONFIG_PATH=/config/local.yaml
    env_file: ./auth/.env

volumes:
  redis_data:
